services:
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: cybersec
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  renoir_codegen:
    depends_on:
      - minio
    image: fabiochini/renoir_codegen
    environment:
      STORE_NAME: prova
      TEAM: prova
      JOB_NAME: prova
      MINIO_HOST: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: cybersec
    volumes:
      - ./resources/kafka.json:/renoir/target.json

volumes:
  minio_data: